version: '3'
services:
  vector-ros-service:
    build:
      context: .
      args:
        vector_ip: <VECTOR_IP> # https://developer.anki.com/vector/docs/troubleshooting.html#can-t-find-vector-s-ip-address
        vector_name: <VECTOR_NAME> # https://developer.anki.com/vector/docs/troubleshooting.html#can-t-find-robot-name
        vector_serial: <VECTOR_SERIAL> # https://developer.anki.com/vector/docs/troubleshooting.html#can-t-find-serial-number
    volumes:
      - .:/catkin_ws/src/vector_ros
    environment:
      - DISPLAY
      - ROS_IPV6=on
      - ROS_MASTER_URI=http://master:11311
    extra_hosts:
    - "master:::1"
    network_mode: host # https://github.com/moby/moby/issues/5708